-- [ACCOUNT_USER_DETAIL]
SELECT USER_ID
     , LOGIN_ID
     , USER_NAME
     , EMAIL
     , ROLE_CODE
     , USE_YN
     , CREATED_AT
     , UPDATED_AT
     , PASSWORD_CHANGE_YN
  FROM "INIT$_TB_USER"
 WHERE USER_ID = :userId
;

-- [ACCOUNT_EMAIL_DUPLICATE_COUNT]
SELECT COUNT(*)
  FROM "INIT$_TB_USER"
 WHERE LOWER(EMAIL) = LOWER(:email)
   AND USER_ID <> :userId
;

-- [ACCOUNT_PROFILE_UPDATE]
UPDATE "INIT$_TB_USER"
   SET USER_NAME = :userName
     , EMAIL = :email
     , UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId
   AND USE_YN = 'Y'
;

-- [ACCOUNT_PASSWORD_HASH]
SELECT PASSWORD_HASH
  FROM "INIT$_TB_USER"
 WHERE USER_ID = :userId
   AND USE_YN = 'Y'
;

-- [ACCOUNT_PASSWORD_UPDATE]
UPDATE "INIT$_TB_USER"
   SET PASSWORD_HASH = :passwordHash
     , PASSWORD_CHANGE_YN = 'Y'
     , UPDATED_AT = SYSTIMESTAMP
 WHERE USER_ID = :userId
   AND USE_YN = 'Y'
;

-- [ACCOUNT_REVOKE_OTHER_SESSIONS]
UPDATE "INIT$_TB_AUTH_SESSION"
   SET REVOKED_AT = LOCALTIMESTAMP
 WHERE USER_ID = :userId
   AND SESSION_TOKEN_HASH <> :currentSessionTokenHash
   AND REVOKED_AT IS NULL
;
