-- [HOME_DASHBOARD_COUNTS]
SELECT (
       SELECT COUNT(*)
         FROM "INIT$_TB_USER"
       ) AS USER_COUNT
     , (
       SELECT COUNT(*)
         FROM "INIT$_TB_USER"
        WHERE USE_YN = 'Y'
       ) AS ACTIVE_USER_COUNT
     , (
       SELECT COUNT(*)
         FROM "INIT$_TB_NOTICE"
        WHERE USE_YN = 'Y'
          AND (POST_START_AT IS NULL OR POST_START_AT <= SYSTIMESTAMP)
          AND (POST_END_AT IS NULL OR POST_END_AT >= SYSTIMESTAMP)
       ) AS NOTICE_COUNT
  FROM DUAL
;

-- [HOME_ACTIVE_NOTICES]
SELECT NOTICE_ID
     , NOTICE_TYPE
     , TITLE
     , CONTENT
     , POST_START_AT
     , POST_END_AT
     , PIN_YN
     , SORT_ORDER
     , FILE_COUNT
     , CREATED_AT
  FROM (
        SELECT N.NOTICE_ID
             , N.NOTICE_TYPE
             , N.TITLE
             , N.CONTENT
             , N.POST_START_AT
             , N.POST_END_AT
             , N.PIN_YN
             , N.SORT_ORDER
             , (
                SELECT COUNT(*)
                  FROM "INIT$_TB_NOTICE_FILE" F
                 WHERE F.NOTICE_ID = N.NOTICE_ID
                   AND F.USE_YN = 'Y'
               ) AS FILE_COUNT
             , N.CREATED_AT
          FROM "INIT$_TB_NOTICE" N
         WHERE N.USE_YN = 'Y'
           AND (N.POST_START_AT IS NULL OR N.POST_START_AT <= SYSTIMESTAMP)
           AND (N.POST_END_AT IS NULL OR N.POST_END_AT >= SYSTIMESTAMP)
         ORDER BY N.PIN_YN DESC
                , N.SORT_ORDER
                , N.CREATED_AT DESC
       )
 WHERE ROWNUM <= :limit
;

-- [HOME_USER_GROWTH_TREND]
WITH MONTHS AS (
     SELECT ADD_MONTHS(TRUNC(SYSDATE, 'MM'), LEVEL - 6) AS MONTH_START
       FROM DUAL
     CONNECT BY LEVEL <= 6
)
SELECT TO_CHAR(M.MONTH_START, 'YYYY-MM') AS MONTH_KEY
     , TO_CHAR(M.MONTH_START, 'MM"월"') AS MONTH_LABEL
     , COUNT(U.USER_ID) AS USER_COUNT
  FROM MONTHS M
  LEFT JOIN "INIT$_TB_USER" U
    ON U.CREATED_AT >= M.MONTH_START
   AND U.CREATED_AT < ADD_MONTHS(M.MONTH_START, 1)
 GROUP BY M.MONTH_START
 ORDER BY M.MONTH_START
;

-- [HOME_SESSION_ACTIVITY_TREND]
WITH DAYS AS (
     SELECT TRUNC(SYSDATE) + LEVEL - 7 AS ACTIVITY_DATE
       FROM DUAL
     CONNECT BY LEVEL <= 7
)
SELECT TO_CHAR(D.ACTIVITY_DATE, 'YYYY-MM-DD') AS DATE_KEY
     , TO_CHAR(D.ACTIVITY_DATE, 'MM/DD') AS DATE_LABEL
     , COUNT(DISTINCT S.USER_ID) AS ACTIVE_USER_COUNT
  FROM DAYS D
  LEFT JOIN "INIT$_TB_AUTH_SESSION" S
    ON S.LAST_SEEN_AT >= D.ACTIVITY_DATE
   AND S.LAST_SEEN_AT < D.ACTIVITY_DATE + 1
 GROUP BY D.ACTIVITY_DATE
 ORDER BY D.ACTIVITY_DATE
;

-- [HOME_NOTICE_TYPE_DISTRIBUTION]
SELECT NOTICE_TYPE
     , COUNT(*) AS NOTICE_COUNT
  FROM "INIT$_TB_NOTICE"
 WHERE USE_YN = 'Y'
   AND (POST_START_AT IS NULL OR POST_START_AT <= SYSTIMESTAMP)
   AND (POST_END_AT IS NULL OR POST_END_AT >= SYSTIMESTAMP)
 GROUP BY NOTICE_TYPE
 ORDER BY NOTICE_COUNT DESC
        , NOTICE_TYPE
;

-- [HOME_AI_TRAINING_SUMMARY]
SELECT COUNT(*) AS TOTAL_COUNT
     , SUM(CASE WHEN STATUS_CODE = 'COMPLETED' THEN 1 ELSE 0 END) AS COMPLETED_COUNT
     , SUM(CASE WHEN STATUS_CODE IN ('PENDING', 'RUNNING') THEN 1 ELSE 0 END) AS ACTIVE_COUNT
     , SUM(CASE WHEN STATUS_CODE = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_COUNT
     , AVG(CASE WHEN STATUS_CODE = 'COMPLETED' THEN ACCURACY_SCORE END) AS AVG_ACCURACY
  FROM "INIT$_TB_AI_TRAINING_RUN"
 WHERE CREATED_AT >= ADD_MONTHS(SYSTIMESTAMP, -1)
;

-- [HOME_AI_TRAINING_TREND]
SELECT TRAINING_RUN_ID
     , MODEL_NAME
     , MODEL_VERSION
     , DATASET_ROW_COUNT
     , EPOCH_COUNT
     , ACCURACY_SCORE
     , LOSS_SCORE
     , RUN_AT
  FROM (
        SELECT TRAINING_RUN_ID
             , MODEL_NAME
             , MODEL_VERSION
             , DATASET_ROW_COUNT
             , EPOCH_COUNT
             , ACCURACY_SCORE
             , LOSS_SCORE
             , NVL(COMPLETED_AT, STARTED_AT) AS RUN_AT
          FROM "INIT$_TB_AI_TRAINING_RUN"
         WHERE STATUS_CODE = 'COMPLETED'
           AND ACCURACY_SCORE IS NOT NULL
         ORDER BY NVL(COMPLETED_AT, STARTED_AT) DESC
       )
 WHERE ROWNUM <= :limit
 ORDER BY RUN_AT
;

-- [HOME_NOTICE_FILES]
SELECT FILE_ID
     , NOTICE_ID
     , FILE_NAME
     , CONTENT_TYPE
     , FILE_SIZE
     , SORT_ORDER
  FROM "INIT$_TB_NOTICE_FILE"
 WHERE NOTICE_ID = :noticeId
   AND USE_YN = 'Y'
 ORDER BY SORT_ORDER
        , FILE_ID
;

-- [HOME_NOTICE_FILE_DOWNLOAD]
SELECT F.FILE_ID
     , F.NOTICE_ID
     , F.FILE_NAME
     , F.CONTENT_TYPE
     , F.FILE_SIZE
     , F.FILE_DATA
  FROM "INIT$_TB_NOTICE_FILE" F
  JOIN "INIT$_TB_NOTICE" N
    ON N.NOTICE_ID = F.NOTICE_ID
 WHERE F.FILE_ID = :fileId
   AND F.USE_YN = 'Y'
   AND N.USE_YN = 'Y'
   AND (N.POST_START_AT IS NULL OR N.POST_START_AT <= SYSTIMESTAMP)
   AND (N.POST_END_AT IS NULL OR N.POST_END_AT >= SYSTIMESTAMP)
;
