/*
 * INIT 시스템 DB 증분 반영 스크립트
 *
 * - 기존 테이블을 DROP하거나 데이터를 삭제하지 않습니다.
 * - 여러 번 실행해도 이미 존재하는 테이블, 컬럼, 제약조건은 건너뜁니다.
 * - 신규 컬럼은 INIT_SYSTEM_DDL.sql의 해당 테이블 맨 뒤에도 같은 순서로 추가합니다.
 * - Oracle은 기존 컬럼 사이에 새 컬럼을 물리적으로 삽입할 수 없으므로,
 *   DROP 없이 컬럼 순서를 유지하려면 신규 컬럼을 두 파일 모두 맨 뒤에 추가해야 합니다.
 */
SET SERVEROUTPUT ON

DECLARE
    FUNCTION OBJECT_EXISTS(
        P_OBJECT_NAME IN VARCHAR2
      , P_OBJECT_TYPE IN VARCHAR2
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM USER_OBJECTS
         WHERE OBJECT_NAME = UPPER(P_OBJECT_NAME)
           AND OBJECT_TYPE = UPPER(P_OBJECT_TYPE);
        RETURN V_COUNT > 0;
    END;

    FUNCTION COLUMN_EXISTS(
        P_TABLE_NAME IN VARCHAR2
      , P_COLUMN_NAME IN VARCHAR2
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = UPPER(P_TABLE_NAME)
           AND COLUMN_NAME = UPPER(P_COLUMN_NAME);
        RETURN V_COUNT > 0;
    END;

    FUNCTION CONSTRAINT_EXISTS(
        P_CONSTRAINT_NAME IN VARCHAR2
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM USER_CONSTRAINTS
         WHERE CONSTRAINT_NAME = UPPER(P_CONSTRAINT_NAME);
        RETURN V_COUNT > 0;
    END;

    PROCEDURE RUN_DDL(
        P_DDL IN CLOB
      , P_LABEL IN VARCHAR2
    ) IS
    BEGIN
        EXECUTE IMMEDIATE P_DDL;
        DBMS_OUTPUT.PUT_LINE('[OK] ' || P_LABEL);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('[ERROR] ' || P_LABEL || ' - ' || SQLERRM);
            RAISE;
    END;

    PROCEDURE CREATE_TABLE_IF_MISSING(
        P_TABLE_NAME IN VARCHAR2
      , P_DDL IN CLOB
    ) IS
    BEGIN
        IF OBJECT_EXISTS(P_TABLE_NAME, 'TABLE') THEN
            DBMS_OUTPUT.PUT_LINE('[SKIP] TABLE ' || P_TABLE_NAME || ' already exists');
        ELSE
            RUN_DDL(P_DDL, 'CREATE TABLE ' || P_TABLE_NAME);
        END IF;
    END;

    PROCEDURE ADD_COLUMN_IF_MISSING(
        P_TABLE_NAME IN VARCHAR2
      , P_COLUMN_NAME IN VARCHAR2
      , P_COLUMN_DEFINITION IN VARCHAR2
    ) IS
    BEGIN
        IF COLUMN_EXISTS(P_TABLE_NAME, P_COLUMN_NAME) THEN
            DBMS_OUTPUT.PUT_LINE(
                '[SKIP] COLUMN ' || P_TABLE_NAME || '.' || P_COLUMN_NAME || ' already exists'
            );
        ELSE
            RUN_DDL(
                'ALTER TABLE "' || UPPER(P_TABLE_NAME) || '" ADD ('
             || '"' || UPPER(P_COLUMN_NAME) || '" ' || P_COLUMN_DEFINITION || ')'
              , 'ADD COLUMN ' || P_TABLE_NAME || '.' || P_COLUMN_NAME
            );
        END IF;
    END;

    PROCEDURE ADD_CONSTRAINT_IF_MISSING(
        P_CONSTRAINT_NAME IN VARCHAR2
      , P_DDL IN CLOB
    ) IS
    BEGIN
        IF CONSTRAINT_EXISTS(P_CONSTRAINT_NAME) THEN
            DBMS_OUTPUT.PUT_LINE(
                '[SKIP] CONSTRAINT ' || P_CONSTRAINT_NAME || ' already exists'
            );
        ELSE
            RUN_DDL(P_DDL, 'ADD CONSTRAINT ' || P_CONSTRAINT_NAME);
        END IF;
    END;

    PROCEDURE CREATE_INDEX_IF_MISSING(
        P_INDEX_NAME IN VARCHAR2
      , P_DDL IN CLOB
    ) IS
    BEGIN
        IF OBJECT_EXISTS(P_INDEX_NAME, 'INDEX') THEN
            DBMS_OUTPUT.PUT_LINE('[SKIP] INDEX ' || P_INDEX_NAME || ' already exists');
        ELSE
            RUN_DDL(P_DDL, 'CREATE INDEX ' || P_INDEX_NAME);
        END IF;
    END;
BEGIN
    /*
     * 2026-08 최초 비밀번호 변경 의무화
     *
     * 기존 사용자는 이미 정상 비밀번호를 사용 중인 것으로 보정하기 위해
     * 최초 ADD 시 Y를 채우고, 이후 신규 기본값은 N으로 변경합니다.
     */
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_USER'
      , 'PASSWORD_CHANGE_YN'
      , 'CHAR(1 BYTE) DEFAULT ''Y'' NOT NULL ENABLE'
    );
    RUN_DDL(
        'ALTER TABLE "INIT$_TB_USER" MODIFY ('
     || '"PASSWORD_CHANGE_YN" DEFAULT ''N'')'
      , 'MODIFY INIT$_TB_USER.PASSWORD_CHANGE_YN DEFAULT'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_USER_PASSWORD_CHANGE'
      , 'ALTER TABLE "INIT$_TB_USER" '
     || 'ADD CONSTRAINT "INIT$_CK_USER_PASSWORD_CHANGE" '
     || 'CHECK ("PASSWORD_CHANGE_YN" IN (''Y'', ''N'')) ENABLE'
    );
    RUN_DDL(
        q'[COMMENT ON COLUMN "INIT$_TB_USER"."PASSWORD_CHANGE_YN" IS 'Initial password changed (Y/N)']'
      , 'COMMENT INIT$_TB_USER.PASSWORD_CHANGE_YN'
    );

    /*
     * 2026-08 포털 디자인 스킨 설정
     *
     * 아래 컬럼 선언과 ADD 호출 순서는 INIT_SYSTEM_DDL.sql의
     * INIT$_TB_SYSTEM_SETTING 컬럼 순서와 동일합니다.
     */
    CREATE_TABLE_IF_MISSING('INIT$_TB_SYSTEM_SETTING', q'[
CREATE TABLE "INIT$_TB_SYSTEM_SETTING" (
    "SETTING_KEY" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "SETTING_VALUE" VARCHAR2(4000 BYTE) NOT NULL ENABLE
  , "SETTING_DESCRIPTION" VARCHAR2(500 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "INIT$_PK_SYSTEM_SETTING" PRIMARY KEY ("SETTING_KEY")
  , CONSTRAINT "INIT$_FK_SYSTEM_SETTING_CREATED_USER" FOREIGN KEY ("CREATED_BY")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_SYSTEM_SETTING_UPDATED_USER" FOREIGN KEY ("UPDATED_BY")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
)
]');

    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'SETTING_KEY'
      , 'VARCHAR2(100 BYTE) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'SETTING_VALUE'
      , 'VARCHAR2(4000 BYTE) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'SETTING_DESCRIPTION'
      , 'VARCHAR2(500 CHAR)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'CREATED_BY'
      , 'NUMBER'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'CREATED_AT'
      , 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'UPDATED_BY'
      , 'NUMBER'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_SYSTEM_SETTING'
      , 'UPDATED_AT'
      , 'TIMESTAMP (6)'
    );

    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_PK_SYSTEM_SETTING'
      , 'ALTER TABLE "INIT$_TB_SYSTEM_SETTING" '
     || 'ADD CONSTRAINT "INIT$_PK_SYSTEM_SETTING" PRIMARY KEY ("SETTING_KEY")'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_FK_SYSTEM_SETTING_CREATED_USER'
      , 'ALTER TABLE "INIT$_TB_SYSTEM_SETTING" '
     || 'ADD CONSTRAINT "INIT$_FK_SYSTEM_SETTING_CREATED_USER" FOREIGN KEY ("CREATED_BY") '
     || 'REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_FK_SYSTEM_SETTING_UPDATED_USER'
      , 'ALTER TABLE "INIT$_TB_SYSTEM_SETTING" '
     || 'ADD CONSTRAINT "INIT$_FK_SYSTEM_SETTING_UPDATED_USER" FOREIGN KEY ("UPDATED_BY") '
     || 'REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE'
    );

    RUN_DDL(
        q'[COMMENT ON TABLE "INIT$_TB_SYSTEM_SETTING" IS 'Portal runtime settings']'
      , 'COMMENT INIT$_TB_SYSTEM_SETTING'
    );

    /*
     * 2026-08 연도별 프로젝트 관리
     *
     * 아래 컬럼 선언과 ADD 호출 순서는 INIT_SYSTEM_DDL.sql의
     * INIT$_TB_PROJECT 컬럼 순서와 동일합니다.
     */
    CREATE_TABLE_IF_MISSING('INIT$_TB_PROJECT', q'[
CREATE TABLE "INIT$_TB_PROJECT" (
    "PROJECT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "PROJECT_YEAR" NUMBER(4) NOT NULL ENABLE
  , "PROJECT_NAME" VARCHAR2(300 CHAR) NOT NULL ENABLE
  , "CUSTOMER_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE
  , "PROJECT_START_DATE" DATE NOT NULL ENABLE
  , "PROJECT_END_DATE" DATE NOT NULL ENABLE
  , "ORDER_AMOUNT_VAT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "CONTRACT_AMOUNT_VAT" NUMBER(18) DEFAULT 0 NOT NULL ENABLE
  , "PARTICIPATION_TYPE_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE
  , "PARTICIPATION_RATE" NUMBER(5, 2) DEFAULT 100 NOT NULL ENABLE
  , "ORDER_DATE" DATE
  , "BID_DATE" DATE
  , "STATUS_CODE" VARCHAR2(30 BYTE) DEFAULT 'PLANNED' NOT NULL ENABLE
  , "DESCRIPTION" VARCHAR2(2000 CHAR)
  , "CREATED_BY" NUMBER
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , "UPDATED_BY" NUMBER
  , "UPDATED_AT" TIMESTAMP (6)
  , CONSTRAINT "INIT$_PK_PROJECT" PRIMARY KEY ("PROJECT_ID")
  , CONSTRAINT "INIT$_FK_PROJECT_CREATED_USER" FOREIGN KEY ("CREATED_BY")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_FK_PROJECT_UPDATED_USER" FOREIGN KEY ("UPDATED_BY")
        REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_YEAR" CHECK ("PROJECT_YEAR" BETWEEN 1900 AND 2100) ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_PERIOD"
        CHECK ("PROJECT_START_DATE" <= "PROJECT_END_DATE") ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_AMOUNTS"
        CHECK ("ORDER_AMOUNT_VAT" >= 0 AND "CONTRACT_AMOUNT_VAT" >= 0) ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_PART_TYPE"
        CHECK ("PARTICIPATION_TYPE_CODE" IN ('LEAD', 'CONSORTIUM', 'SUBCONTRACT')) ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_PART_RATE"
        CHECK ("PARTICIPATION_RATE" BETWEEN 0 AND 100) ENABLE
  , CONSTRAINT "INIT$_CK_PROJECT_STATUS"
        CHECK ("STATUS_CODE" IN ('PLANNED', 'BIDDING', 'CONTRACTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')) ENABLE
)
]');

    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_ID'
      , 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_YEAR'
      , 'NUMBER(4) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_NAME'
      , 'VARCHAR2(300 CHAR) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'CUSTOMER_NAME'
      , 'VARCHAR2(200 CHAR) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_START_DATE'
      , 'DATE NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PROJECT_END_DATE'
      , 'DATE NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'ORDER_AMOUNT_VAT'
      , 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'CONTRACT_AMOUNT_VAT'
      , 'NUMBER(18) DEFAULT 0 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PARTICIPATION_TYPE_CODE'
      , 'VARCHAR2(30 BYTE) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'PARTICIPATION_RATE'
      , 'NUMBER(5, 2) DEFAULT 100 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'ORDER_DATE'
      , 'DATE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'BID_DATE'
      , 'DATE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'STATUS_CODE'
      , 'VARCHAR2(30 BYTE) DEFAULT ''PLANNED'' NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'DESCRIPTION'
      , 'VARCHAR2(2000 CHAR)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'CREATED_BY'
      , 'NUMBER'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'CREATED_AT'
      , 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'UPDATED_BY'
      , 'NUMBER'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_PROJECT'
      , 'UPDATED_AT'
      , 'TIMESTAMP (6)'
    );

    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_PK_PROJECT'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_PK_PROJECT" '
     || 'PRIMARY KEY ("PROJECT_ID")'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_FK_PROJECT_CREATED_USER'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_FK_PROJECT_CREATED_USER" '
     || 'FOREIGN KEY ("CREATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_FK_PROJECT_UPDATED_USER'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_FK_PROJECT_UPDATED_USER" '
     || 'FOREIGN KEY ("UPDATED_BY") REFERENCES "INIT$_TB_USER" ("USER_ID") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_YEAR'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_YEAR" '
     || 'CHECK ("PROJECT_YEAR" BETWEEN 1900 AND 2100) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_PERIOD'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_PERIOD" '
     || 'CHECK ("PROJECT_START_DATE" <= "PROJECT_END_DATE") ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_AMOUNTS'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_AMOUNTS" '
     || 'CHECK ("ORDER_AMOUNT_VAT" >= 0 AND "CONTRACT_AMOUNT_VAT" >= 0) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_PART_TYPE'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_PART_TYPE" '
     || 'CHECK ("PARTICIPATION_TYPE_CODE" IN (''LEAD'', ''CONSORTIUM'', ''SUBCONTRACT'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_PART_RATE'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_PART_RATE" '
     || 'CHECK ("PARTICIPATION_RATE" BETWEEN 0 AND 100) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_PROJECT_STATUS'
      , 'ALTER TABLE "INIT$_TB_PROJECT" ADD CONSTRAINT "INIT$_CK_PROJECT_STATUS" '
     || 'CHECK ("STATUS_CODE" IN (''PLANNED'', ''BIDDING'', ''CONTRACTED'', '
     || '''IN_PROGRESS'', ''COMPLETED'', ''CANCELLED'')) ENABLE'
    );
    CREATE_INDEX_IF_MISSING(
        'INIT$_IX_PROJECT_YEAR_STATUS'
      , 'CREATE INDEX "INIT$_IX_PROJECT_YEAR_STATUS" '
     || 'ON "INIT$_TB_PROJECT" ("PROJECT_YEAR", "STATUS_CODE", "PROJECT_ID")'
    );
    CREATE_INDEX_IF_MISSING(
        'INIT$_IX_PROJECT_PERIOD'
      , 'CREATE INDEX "INIT$_IX_PROJECT_PERIOD" '
     || 'ON "INIT$_TB_PROJECT" ("PROJECT_START_DATE", "PROJECT_END_DATE")'
    );
    RUN_DDL(
        q'[COMMENT ON TABLE "INIT$_TB_PROJECT" IS 'Annual IT project management']'
      , 'COMMENT INIT$_TB_PROJECT'
    );

    /*
     * 2026-07 AI 학습 트렌드 대시보드
     *
     * 아래 컬럼 선언과 ADD 호출 순서는 INIT_SYSTEM_DDL.sql의
     * INIT$_TB_AI_TRAINING_RUN 컬럼 순서와 동일합니다.
     */
    CREATE_TABLE_IF_MISSING('INIT$_TB_AI_TRAINING_RUN', q'[
CREATE TABLE "INIT$_TB_AI_TRAINING_RUN" (
    "TRAINING_RUN_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE
  , "MODEL_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE
  , "MODEL_VERSION" VARCHAR2(100 CHAR)
  , "STATUS_CODE" VARCHAR2(30 BYTE) DEFAULT 'PENDING' NOT NULL ENABLE
  , "DATASET_ROW_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE
  , "EPOCH_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE
  , "ACCURACY_SCORE" NUMBER(12, 8)
  , "LOSS_SCORE" NUMBER(12, 8)
  , "STARTED_AT" TIMESTAMP (6)
  , "COMPLETED_AT" TIMESTAMP (6)
  , "CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE
  , CONSTRAINT "INIT$_PK_AI_TRAINING_RUN" PRIMARY KEY ("TRAINING_RUN_ID")
  , CONSTRAINT "INIT$_CK_AI_TRAINING_STATUS"
        CHECK ("STATUS_CODE" IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')) ENABLE
  , CONSTRAINT "INIT$_CK_AI_TRAINING_ACCURACY"
        CHECK ("ACCURACY_SCORE" IS NULL OR ("ACCURACY_SCORE" >= 0 AND "ACCURACY_SCORE" <= 1)) ENABLE
)
]');

    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'TRAINING_RUN_ID'
      , 'NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'MODEL_NAME'
      , 'VARCHAR2(200 CHAR) NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'MODEL_VERSION'
      , 'VARCHAR2(100 CHAR)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'STATUS_CODE'
      , 'VARCHAR2(30 BYTE) DEFAULT ''PENDING'' NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'DATASET_ROW_COUNT'
      , 'NUMBER DEFAULT 0 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'EPOCH_COUNT'
      , 'NUMBER DEFAULT 0 NOT NULL ENABLE'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'ACCURACY_SCORE'
      , 'NUMBER(12, 8)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'LOSS_SCORE'
      , 'NUMBER(12, 8)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'STARTED_AT'
      , 'TIMESTAMP (6)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'COMPLETED_AT'
      , 'TIMESTAMP (6)'
    );
    ADD_COLUMN_IF_MISSING(
        'INIT$_TB_AI_TRAINING_RUN'
      , 'CREATED_AT'
      , 'TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE'
    );

    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_PK_AI_TRAINING_RUN'
      , 'ALTER TABLE "INIT$_TB_AI_TRAINING_RUN" '
     || 'ADD CONSTRAINT "INIT$_PK_AI_TRAINING_RUN" PRIMARY KEY ("TRAINING_RUN_ID")'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_AI_TRAINING_STATUS'
      , 'ALTER TABLE "INIT$_TB_AI_TRAINING_RUN" '
     || 'ADD CONSTRAINT "INIT$_CK_AI_TRAINING_STATUS" '
     || 'CHECK ("STATUS_CODE" IN (''PENDING'', ''RUNNING'', ''COMPLETED'', ''FAILED'', ''CANCELLED'')) ENABLE'
    );
    ADD_CONSTRAINT_IF_MISSING(
        'INIT$_CK_AI_TRAINING_ACCURACY'
      , 'ALTER TABLE "INIT$_TB_AI_TRAINING_RUN" '
     || 'ADD CONSTRAINT "INIT$_CK_AI_TRAINING_ACCURACY" '
     || 'CHECK ("ACCURACY_SCORE" IS NULL '
     || 'OR ("ACCURACY_SCORE" >= 0 AND "ACCURACY_SCORE" <= 1)) ENABLE'
    );
    CREATE_INDEX_IF_MISSING(
        'INIT$_IX_AI_TRAINING_STATUS'
      , 'CREATE INDEX "INIT$_IX_AI_TRAINING_STATUS" '
     || 'ON "INIT$_TB_AI_TRAINING_RUN" ("STATUS_CODE", "COMPLETED_AT")'
    );
    RUN_DDL(
        q'[COMMENT ON TABLE "INIT$_TB_AI_TRAINING_RUN" IS 'AI model training run metrics']'
      , 'COMMENT INIT$_TB_AI_TRAINING_RUN'
    );
END;
/
