-- [PROJECT_ASSIGNMENT_REFERENCE_PROJECTS]
SELECT PROJECT_ID
     , PROJECT_YEAR
     , PROJECT_NAME
     , PROJECT_START_DATE
     , PROJECT_END_DATE
     , CONTRACT_AMOUNT_VAT
  FROM "INIT$_TB_PROJECT"
 WHERE STATUS_CODE <> 'CANCELLED'
 ORDER BY PROJECT_YEAR DESC
        , PROJECT_NAME
;

-- [PROJECT_ASSIGNMENT_REFERENCE_USERS]
SELECT USER_ID
     , EMPLOYEE_NO
     , USER_NAME
     , DEPARTMENT_NAME
     , POSITION_NAME
     , JOB_TITLE
  FROM "INIT$_TB_USER"
 WHERE USE_YN = 'Y'
   AND EMPLOYMENT_STATUS_CODE IN ('ACTIVE', 'LEAVE')
 ORDER BY USER_NAME
        , USER_ID
;

-- [PROJECT_ASSIGNMENT_PROJECT]
SELECT PROJECT_ID
     , PROJECT_NAME
     , PROJECT_START_DATE
     , PROJECT_END_DATE
     , CONTRACT_AMOUNT_VAT
     , PARTICIPATION_RATE
  FROM "INIT$_TB_PROJECT"
 WHERE PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_COMPANY_LIST]
SELECT C.PROJECT_COMPANY_ID
     , C.PROJECT_ID
     , C.COMPANY_NAME
     , C.PARTICIPATION_TYPE_CODE
     , C.SHARE_RATE
     , ROUND(P.CONTRACT_AMOUNT_VAT * C.SHARE_RATE / 100) AS ALLOCATED_SALES_AMOUNT
     , NVL(A.TOTAL_COST_AMOUNT, 0) AS TOTAL_COST_AMOUNT
     , NVL(A.TOTAL_SALES_AMOUNT, 0) AS TOTAL_SALES_AMOUNT
     , NVL(A.OPERATING_PROFIT, 0) AS OPERATING_PROFIT
     , C.NOTE
  FROM "INIT$_TB_PROJECT_COMPANY" C
  JOIN "INIT$_TB_PROJECT" P
    ON P.PROJECT_ID = C.PROJECT_ID
  LEFT JOIN (
        SELECT PROJECT_COMPANY_ID
             , SUM(TOTAL_COST_AMOUNT) AS TOTAL_COST_AMOUNT
             , SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
             , SUM(OPERATING_PROFIT) AS OPERATING_PROFIT
          FROM "INIT$_TB_PROJECT_ASSIGNMENT"
         GROUP BY PROJECT_COMPANY_ID
       ) A
    ON A.PROJECT_COMPANY_ID = C.PROJECT_COMPANY_ID
 WHERE C.PROJECT_ID = :projectId
 ORDER BY C.PROJECT_COMPANY_ID
;

-- [PROJECT_ASSIGNMENT_COMPANY_INSERT]
INSERT INTO "INIT$_TB_PROJECT_COMPANY" (
    PROJECT_ID
  , COMPANY_NAME
  , PARTICIPATION_TYPE_CODE
  , SHARE_RATE
  , NOTE
  , CREATED_BY
  , CREATED_AT
) VALUES (
    :projectId
  , :companyName
  , :participationTypeCode
  , :shareRate
  , :note
  , :userId
  , SYSTIMESTAMP
)
RETURNING PROJECT_COMPANY_ID INTO :projectCompanyIdOut
;

-- [PROJECT_ASSIGNMENT_COMPANY_UPDATE]
UPDATE "INIT$_TB_PROJECT_COMPANY"
   SET COMPANY_NAME = :companyName
     , PARTICIPATION_TYPE_CODE = :participationTypeCode
     , SHARE_RATE = :shareRate
     , NOTE = :note
     , UPDATED_BY = :userId
     , UPDATED_AT = SYSTIMESTAMP
 WHERE PROJECT_COMPANY_ID = :projectCompanyId
   AND PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_COMPANY_DELETE]
DELETE FROM "INIT$_TB_PROJECT_COMPANY"
 WHERE PROJECT_COMPANY_ID = :projectCompanyId
   AND PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_COMPANY_BELONGS]
SELECT COUNT(*)
  FROM "INIT$_TB_PROJECT_COMPANY"
 WHERE PROJECT_COMPANY_ID = :projectCompanyId
   AND PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_COMPANY_OTHER_SHARE]
SELECT NVL(SUM(SHARE_RATE), 0)
  FROM "INIT$_TB_PROJECT_COMPANY"
 WHERE PROJECT_ID = :projectId
   AND (:projectCompanyId IS NULL OR PROJECT_COMPANY_ID <> :projectCompanyId)
;

-- [PROJECT_ASSIGNMENT_LIST]
SELECT A.ASSIGNMENT_ID
     , A.PROJECT_ID
     , A.USER_ID
     , U.EMPLOYEE_NO
     , U.USER_NAME
     , U.DEPARTMENT_NAME
     , U.POSITION_NAME
     , U.JOB_TITLE
     , A.PROJECT_COMPANY_ID
     , C.COMPANY_NAME
     , A.ASSIGNMENT_START_DATE
     , A.ASSIGNMENT_END_DATE
     , A.ALLOCATION_TYPE_CODE
     , A.DEFAULT_MM
     , A.WEEKLY_DAY_CODES
     , A.MONTHLY_ALLOCATION_JSON
     , A.TOTAL_MM
     , A.COST_UNIT_PRICE
     , A.SALES_UNIT_PRICE
     , A.TOTAL_COST_AMOUNT
     , A.TOTAL_SALES_AMOUNT
     , A.OPERATING_PROFIT
     , A.NOTE
  FROM "INIT$_TB_PROJECT_ASSIGNMENT" A
  JOIN "INIT$_TB_USER" U
    ON U.USER_ID = A.USER_ID
  LEFT JOIN "INIT$_TB_PROJECT_COMPANY" C
    ON C.PROJECT_COMPANY_ID = A.PROJECT_COMPANY_ID
 WHERE A.PROJECT_ID = :projectId
 ORDER BY A.ASSIGNMENT_START_DATE
        , U.USER_NAME
        , A.ASSIGNMENT_ID
;

-- [PROJECT_ASSIGNMENT_SUMMARY]
SELECT P.CONTRACT_AMOUNT_VAT
     , NVL(C.COMPANY_SHARE_RATE, 0) AS COMPANY_SHARE_RATE
     , NVL(C.COMPANY_ALLOCATED_AMOUNT, 0) AS COMPANY_ALLOCATED_AMOUNT
     , NVL(A.TOTAL_MM, 0) AS TOTAL_MM
     , NVL(A.TOTAL_COST_AMOUNT, 0) AS TOTAL_COST_AMOUNT
     , NVL(A.TOTAL_SALES_AMOUNT, 0) AS TOTAL_SALES_AMOUNT
     , NVL(A.OPERATING_PROFIT, 0) AS OPERATING_PROFIT
  FROM "INIT$_TB_PROJECT" P
  LEFT JOIN (
        SELECT PROJECT_ID
             , SUM(SHARE_RATE) AS COMPANY_SHARE_RATE
             , SUM(ALLOCATED_AMOUNT) AS COMPANY_ALLOCATED_AMOUNT
          FROM (
                SELECT C.PROJECT_ID
                     , C.SHARE_RATE
                     , ROUND(P2.CONTRACT_AMOUNT_VAT * C.SHARE_RATE / 100) AS ALLOCATED_AMOUNT
                  FROM "INIT$_TB_PROJECT_COMPANY" C
                  JOIN "INIT$_TB_PROJECT" P2
                    ON P2.PROJECT_ID = C.PROJECT_ID
               )
         GROUP BY PROJECT_ID
       ) C
    ON C.PROJECT_ID = P.PROJECT_ID
  LEFT JOIN (
        SELECT PROJECT_ID
             , SUM(TOTAL_MM) AS TOTAL_MM
             , SUM(TOTAL_COST_AMOUNT) AS TOTAL_COST_AMOUNT
             , SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
             , SUM(OPERATING_PROFIT) AS OPERATING_PROFIT
          FROM "INIT$_TB_PROJECT_ASSIGNMENT"
         GROUP BY PROJECT_ID
       ) A
    ON A.PROJECT_ID = P.PROJECT_ID
 WHERE P.PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_INSERT]
INSERT INTO "INIT$_TB_PROJECT_ASSIGNMENT" (
    PROJECT_ID
  , USER_ID
  , PROJECT_COMPANY_ID
  , ASSIGNMENT_START_DATE
  , ASSIGNMENT_END_DATE
  , ALLOCATION_TYPE_CODE
  , DEFAULT_MM
  , WEEKLY_DAY_CODES
  , MONTHLY_ALLOCATION_JSON
  , TOTAL_MM
  , COST_UNIT_PRICE
  , SALES_UNIT_PRICE
  , TOTAL_COST_AMOUNT
  , TOTAL_SALES_AMOUNT
  , OPERATING_PROFIT
  , NOTE
  , CREATED_BY
  , CREATED_AT
) VALUES (
    :projectId
  , :employeeUserId
  , :projectCompanyId
  , :assignmentStartDate
  , :assignmentEndDate
  , :allocationTypeCode
  , :defaultMm
  , :weeklyDayCodes
  , :monthlyAllocationJson
  , :totalMm
  , :costUnitPrice
  , :salesUnitPrice
  , :totalCostAmount
  , :totalSalesAmount
  , :operatingProfit
  , :note
  , :userId
  , SYSTIMESTAMP
)
RETURNING ASSIGNMENT_ID INTO :assignmentIdOut
;

-- [PROJECT_ASSIGNMENT_UPDATE]
UPDATE "INIT$_TB_PROJECT_ASSIGNMENT"
   SET USER_ID = :employeeUserId
     , PROJECT_COMPANY_ID = :projectCompanyId
     , ASSIGNMENT_START_DATE = :assignmentStartDate
     , ASSIGNMENT_END_DATE = :assignmentEndDate
     , ALLOCATION_TYPE_CODE = :allocationTypeCode
     , DEFAULT_MM = :defaultMm
     , WEEKLY_DAY_CODES = :weeklyDayCodes
     , MONTHLY_ALLOCATION_JSON = :monthlyAllocationJson
     , TOTAL_MM = :totalMm
     , COST_UNIT_PRICE = :costUnitPrice
     , SALES_UNIT_PRICE = :salesUnitPrice
     , TOTAL_COST_AMOUNT = :totalCostAmount
     , TOTAL_SALES_AMOUNT = :totalSalesAmount
     , OPERATING_PROFIT = :operatingProfit
     , NOTE = :note
     , UPDATED_BY = :userId
     , UPDATED_AT = SYSTIMESTAMP
 WHERE ASSIGNMENT_ID = :assignmentId
   AND PROJECT_ID = :projectId
;

-- [PROJECT_ASSIGNMENT_DELETE]
DELETE FROM "INIT$_TB_PROJECT_ASSIGNMENT"
 WHERE ASSIGNMENT_ID = :assignmentId
   AND PROJECT_ID = :projectId
;
