-- [SITE_HOMEPAGE_SKIN_GET]
SELECT SETTING_VALUE
  FROM "INIT$_TB_SYSTEM_SETTING"
 WHERE SETTING_KEY = 'HOMEPAGE_SKIN'
;

-- [SITE_HOMEPAGE_SKIN_UPSERT]
MERGE INTO "INIT$_TB_SYSTEM_SETTING" TARGET
USING (
      SELECT 'HOMEPAGE_SKIN' AS SETTING_KEY
           , :settingValue AS SETTING_VALUE
           , :updatedBy AS UPDATED_BY
        FROM DUAL
      ) SOURCE
   ON (TARGET.SETTING_KEY = SOURCE.SETTING_KEY)
 WHEN MATCHED THEN
      UPDATE
         SET TARGET.SETTING_VALUE = SOURCE.SETTING_VALUE
           , TARGET.UPDATED_BY = SOURCE.UPDATED_BY
           , TARGET.UPDATED_AT = SYSTIMESTAMP
 WHEN NOT MATCHED THEN
      INSERT (
          SETTING_KEY
        , SETTING_VALUE
        , SETTING_DESCRIPTION
        , CREATED_BY
        , CREATED_AT
        , UPDATED_BY
        , UPDATED_AT
      )
      VALUES (
          SOURCE.SETTING_KEY
        , SOURCE.SETTING_VALUE
        , 'Portal login and workspace visual skin'
        , SOURCE.UPDATED_BY
        , SYSTIMESTAMP
        , SOURCE.UPDATED_BY
        , SYSTIMESTAMP
      )
;
